// Generated by CoffeeScript 2.5.1
var SerialPort, chalk, debug, errMsg, serial;

debug = require('debug')('iot_sensor.recv.serial');

chalk = require('chalk');

SerialPort = require('serialport');

errMsg = function(message) {
  return console.log(chalk.bgRed(message));
};

module.exports = serial = function(options) {
  var Parser, port;
  Parser = SerialPort.parsers[options.parser];
  port = new SerialPort(options.path, options.openOptions);
  port.parser = port.pipe(new Parser(options.paserOptions));
  port.on('close', function(closed) {
    return console.log(chalk.red('client closed'), closed);
  });
  port.on('error', function(error) {
    return errMsg(error.message);
  });
  return port.on('open', function() {
    return console.log('open on:%s@%s', port.path, port.baudRate);
  });
};
