// Generated by CoffeeScript 2.5.1
var dgram, log, udpClient;

log = require("../utils/log")('udpClient');

dgram = require('dgram');

module.exports = udpClient = function() {
  var socket;
  socket = dgram.createSocket('udp4');
  socket.on('close', function(closed) {
    return log.warn('closed');
  });
  socket.on('connect', function() {
    var address, port;
    ({address, port} = socket.remoteAddress());
    return log.address(address, port, 'connected');
  });
  socket.on('message', function(data, rinfo) {
    log.address(rinfo.address, rinfo.port, rinfo.size);
    return console.log(data);
  });
  socket.on('error', function(error) {
    return log.error(error.message);
  });
  socket.liveConnect = function(options, timeout = 5000) {
    var connect;
    connect = function() {
      return socket.connect(options.port, options.host);
    };
    socket.on('close', function() {
      return setTimeout(connect, timeout);
    });
    return connect();
  };
  return socket;
};
