// Generated by CoffeeScript 2.5.1
var dgram, log, udpServer;

log = require('../utils/log')('udpServer');

dgram = require('dgram');

module.exports = udpServer = function() {
  var server;
  server = dgram.createSocket('udp4');
  server.on('close', function(closed) {
    return log.warn('closed');
  });
  server.on('error', function(error) {
    return log.error(error.message);
  });
  server.on('message', function(data, rinfo) {
    log.address(rinfo.address, rinfo.port, rinfo.size);
    return console.log(data);
  });
  server.on('listening', function(socket) {
    var address, port;
    ({address, port} = server.address());
    return log.address(address, port, 'listening');
  });
  server.listen = function(options) {
    return server.bind(options.port, options.host);
  };
  return server;
};
